### ISSUE TITLE
"alprScanner?.scanImage(image:..." seems not working

### ISSUE THREAD

**Issue by sensei71** [yasirmturk/openalpr-swift#1]
Hi,
first of all I want to say that this class working well with static image, but i cannot used it with UIIMAGE.
Another thing that can be useful: plate position (x,y) is not returning in plate object, maybe will be implemented

Regards and congratulation

Rodolfo

here my code

// Convert cropped image ref to UIImage
        let imageToSave = UIImage(cgImage: imageRef, scale: 1.0, orientation: .right)
        
        print("image: \(String(describing: imageToSave.size))") // Your Image
        self.captureImageView.image = imageToSave
        self.captureImageView.isHidden = false
        
        if let data = UIImageJPEGRepresentation(imageToSave, 1) {
            let filename = getDocumentsDirectory().appendingPathComponent("targa.jpg")
            try? data.write(to: filename)
            let imagePath = filename.path
            
            
            // let imagePath = Bundle.main.path(forResource: "targadk", ofType: "jpg")
            let alprScanner = OAScanner(country: "eu", patternRegion: "dk")
            
            //alprScanner?.scanImage(imageToSave, onSuccess: {
            alprScanner?.scanImage(atPath: imagePath , onSuccess: {
                // alprScanner?.scanImage(newPhoto , onSuccess: {
                (plates) in
                plates?.forEach({ (plate) in
                    print("result: \(plate.number)")
                    
                    print(plate)
                })
            }, onFailure: { (error) in
                print("error: \(String(describing: error?.localizedDescription))")
            })

            
            
        }

**Comment by yasirmturk** [comment]
According to my experience with the provided trained data set, It works best when you 
- Capture the picture of plate along with some area around it
- Downsize your `UIImage` resolution to somewhere between [1280 - 480] i.e. 1280x720 or 640x480
- Fix the orientation of `UIImage` before passing it to the scanner
- Capture or Crop the image in landscape 
- Make sure you have selected correct country and region

Still if you are having troubles, please send me the picture that you are trying to scan

**Comment by yasirmturk** [comment]
detected region you can get by implementing the delegate method
`- (void)didScanResults:(OAResults *)results;`
read the `platePoints` of the first plate in `results`

**Comment by sensei71** [comment]
Scanning works perfectly. My problem is passing directly UIIMAGE in OAScanner(image:. 
Actually I solved storing UIIMAGE taken from Camera in doc dir and then scanning with OAScanner(atPath:

2nd issue is retrieving results info, specially positioning of plate. You suggested to implement delegate method. I tried but funcs don’t fire…

Here’s my code

class AlprController: UIViewController, AVCapturePhotoCaptureDelegate, OAScannerDelegate

….


    //MARK: Callback Delegate

    func didScanResults(_ results: OAResults!) {
        print("didScanResults \(results)")
    }

    func didScanResultsJSON(_ results: String!) {
        print("didScanResultsJSON \(results)")
    }
    
    func didScanBestPlates(_ bestPlates: [OAPlate]!) {
        print("didScanBestPlates")
    }


Regards

Rodolfo

**Comment by yasirmturk** [comment]
when you write `UIImage` to file it stores meta date like orientation along with it... but in case of passing it directly you need to fix the orientation yourself

and 
`
func didScanResults(_ results: OAResults!) {
        for plate in results.plates {
            for point in plate.platePoints {
                let pt = point.cgPointValue
                let newPt = CGPoint(x: pt.x, y: pt.y)
            }
        }
    }
`

**Comment by sensei71** [comment]
final class AlprController: UIViewController, AVCapturePhotoCaptureDelegate, OAScannerDelegate {
    
    var alprScanner = OAScanner()


    //MARK: Callback Delegate

    func didScanResults(_ results: OAResults!) {
        print("didScanResults")

        for plate in results.plates {
            for point in plate.platePoints {
                let pt = (point as AnyObject).cgPointValue
                let newPt = CGPoint(x: (pt?.x)!, y: (pt?.y)!)
                print(newPt)

            }
            
        }
        
    }


    override func viewDidLoad() {
        super.viewDidLoad()
        
        alprScanner.delegate = self

After using alprScanner.scanImage(atPath:

The program don’t fire didScanResults I don’t know why, any idea

Regards

Rodolfo

**Comment by yasirmturk** [comment]
remove 
`func didScanResultsJSON(_ results: String!) {
        print("didScanResultsJSON \(results)")
    }`

then it will fire

**Comment by sensei71** [comment]
still not firing… tried also with only didScanResultsJSON, but nothing… seems not working delegate protocol… I’m using swift 4.0 in last xcode
 version.

Regards
R.

**Comment by sensei71** [comment]
ahahah

I solved

var alprScanner = OAScanner(country: "eu", patternRegion: "dk”)

instead of 

var alprScanner = OAScanner()

before

alprScanner?.delegate = self



R.

**Comment by yasirmturk** [comment]
great thanks

**Comment by Luxonis-Brandon** [comment]
Hey guys, 

Sorry for a late follow-up question here.  So I too am trying to get the plate coordinates, and can't quite seem to get them (despite trying to piece together the above... not sure what I'm missing).

I have, however, gotten the coordinates of the characters in the plates (cheat-y code below):
```
let alprScanner = OAScanner(country: "us", patternRegion: "co")
        alprScanner?.scanImage(photo.image, onSuccess: { (plates) in
            plates?.forEach({ (plate) in
                print("result (oh ya!): \(String(describing: plate.number)), probability: \(String(describing: plate.confidence))")
                self.licensePlateText.text = String(describing: plate.number!)
                print(plate.characters[0].corners)
                print(plate.characters[0].character)
                
            })
            }, onFailure: { (error) in
                print("error, oh no!: \(String(describing:error?.localizedDescription))")
        })
```

And this prints, as it should:

> result (oh ya!): Optional("WBFYDND"), probability: 81.44639
> Optional([NSPoint: {1215, 1927}, NSPoint: {1278, 1925}, NSPoint: {1287, 2146}, NSPoint: {1224, 2148}])
> Optional("W")

Now, I'm stuck when it comes to the required delegate bits to get the bounding box of the license plate.

Where should I define the functions?   I did find the following in "OAScanner.h"
```
@optional
- (void)didScanResults:(OAResults *)results;

- (void)didScanResultsJSON:(NSString *)results;

- (void)didScanBestPlates:(NSArray<OAPlate *> *)bestPlates;

- (void)didScanPlateResult:(OAPlateResult *)plateResult;

- (void)didFailToLoadwithError:(NSError *)error;

@end
```

And the `didScanPlateResult` is definitely what I want to use, like sensei71 mentioned.

Where should I put the delegate functions, and how should I call them?
Do I call them after having called the scanImage function?

Thanks in advance!

**Comment by yasirmturk** [comment]
You can use
```
func didScanPlateResult(_ plateResult: OAPlateResult!) {
        DispatchQueue.main.async {
            self.updatePlateBorder(result: plateResult)
            if plateResult.bestPlate.confidence > 90 {
                self.textField.text = plateResult.bestPlate.number
            }
        }
    }
```
and
```
fileprivate func updatePlateBorder(result: OAPlateResult?) {
        guard let result = result else {
            UIView.animate(withDuration: 0.2, animations: {
                self.borderView.alpha = 0
            })
            return
        }
        let widthScale = CGFloat(result.cols) / borderView.bounds.width
        let heightScale = CGFloat(result.rows) / borderView.bounds.height
        if let points = result.platePoints {
            var newPoints = [NSValue]()
            for i in 0..<points.count {
                let pt = points[i].cgPointValue
                let newPt = CGPoint(x: pt.x / widthScale, y: pt.y / heightScale)
                newPoints.append(NSValue(cgPoint: newPt))
            }
            UIView.animate(withDuration: 0.1) {
                self.borderView.alpha = 1
                self.borderView.updateCorners(newPoints)
            }
        }
    }
```

**Comment by yasirmturk** [comment]
here is the border view class 
https://github.com/cardash/react-native-openalpr/blob/master/ios/RecognizedPlateBorderView.h

**Comment by Luxonis-Brandon** [comment]
Awesome, thanks a ton for the help!  Parsing through it now.

(And thanks equally for the framework itself!)

**Comment by yasirmturk** [comment]
you are welcome :)

**Comment by Luxonis-Brandon** [comment]
So I was able to pull in the RecognizedPlateBorderView.h by adding the .h and .mm to the Podfile project, and then making sure the .h is in both the OpenALPRSwift-umbrella.h file and also added to Build Phases > Headers.

However, I don't think that's what I'm looking for actually.  

From your example above, you're actually calling on results of the PlateScanner.mm from the ReactNative project, here:
https://github.com/cardash/react-native-openalpr/blob/master/ios/PlateScanner.mm

Now, this is fine, I guess I could use that project instead... but, is there a way to do this with your framework?  Or should I just move to the React Native framework instead?  I tried using PlateScanner.mm (and PlateScanner.h) in your framework/podfile, but it doesn't work because the ReactNative framework has different dependencies.

Thoughts?

Thanks again!

**Comment by Luxonis-Brandon** [comment]
In other words I'm just looking to get OAPlateResult filled, but I don't see a function to do that in the current framework.  The React Native Framework has the equivalent, but I don't see it in this Swift framework.

And to clarify, OAScanner seems to return only type OAPLate, not OAPlateResult, as far as I can tell.

Am I missing something?

Thanks again!

**Comment by Luxonis-Brandon** [comment]
Yep, according to the definition, it does return, or rather is typedef'ed to, OAPlate type:
typedef void(^onPlateScanSuccess)(NSArray<OAPlate *> *);

(in here: https://github.com/yasirmturk/openalpr-swift/blob/master/openalpr-swift/OAScanner.h)

**Comment by yasirmturk** [comment]
so, you found what you looking for?

**Comment by sensei71** [comment]
Yes, thanks

Regards
R.

**Comment by Luxonis-Brandon** [comment]
So I have not yet.  

I can't figure out how to get OAPlateResult populated.  What do I call to populate it?

Right now I'm calling OAScanner, but it returns type OAPlate, which doesn't include the plate coordinates.

Thanks again!

**Comment by yasirmturk** [comment]
that is the delegate method 
`didScanPlateResult`
what are you getting in that method?

**Comment by Luxonis-Brandon** [comment]
Thanks!  

So when I try to call it, it says it needs type OAPlateResult, which was what I'm trying to get from it.

So I think it's as simple as me not knowing how to use that delegate.  I'm new to Swift (this is my ~3rd day programming in it), so it could be me doing something really dumb.

How are you getting results from didScanPlateResult?

Thanks again!

**Comment by yasirmturk** [comment]
i have update my comment [above](https://github.com/yasirmturk/openalpr-swift/issues/1#issuecomment-426146337), now you can see the proper code

**Comment by yasirmturk** [comment]
i am passing `OAPlateResult` to `updatePlateBorder(result: plateResult)`

**Comment by Luxonis-Brandon** [comment]
So my problem is I don't know how to get OAPlateResult to start with.  Where are you getting it?

**Comment by yasirmturk** [comment]
to use the delegate 
```
if let scanner = OAScanner(country: "eu", patternRegion: "dk") {
            scanner.delegate = self // Here we set the delegate 
            scanner.setTopN(1)
    // scanner.scanImage... // use this method as usual
}
```
and then 

```
extension CameraViewController: OAScannerDelegate {
    // Here you will get the complete results
    func didScanPlateResult(_ plateResult: OAPlateResult!) {
        DispatchQueue.main.async {
            //self.updatePlateBorder(result: plateResult)
        }
    }
```

**Comment by Luxonis-Brandon** [comment]
Perfect.  I think this is what I was missing.  Trying it out.

Thanks again!

**Comment by Luxonis-Brandon** [comment]
Yes, that was exactly it.  I'm now getting OAPlateResult, as desired, including the plate points:

```
plateResult: <OAPlateResult: 0x28110ca80>
plateResult.bestPlate.number!: 026UAT
plateResult.platePoints!: [NSPoint: {805, 1506}, NSPoint: {2296, 1506}, NSPoint: {2268, 2596}, NSPoint: {805, 2596}]
```

Thanks again for all the help!  Everything is working now.  :-)
