### ISSUE TITLE
Crashing in simulator 

### ISSUE THREAD

**Issue by skarsad04** [yasirmturk/openalpr-swift#12]
After installing pod, I am trying to run the code and  build is successful but unable to open the app in simulator.

dyld: lazy symbol binding failed: can't resolve symbol ___cxa_guard_acquire in /Users/52127608/Library/Developer/CoreSimulator/Devices/FC163F57-3BF9-4CDA-9E24-DAA7C8EADBC1/data/Containers/Bundle/Application/A97B39AF-FC7A-4AC0-9503-C36DF7265780/NJEZPass.app/NJEZPass because dependent dylib #1 could not be loaded
dyld: can't resolve symbol ___cxa_guard_acquire in /Users/52127608/Library/Developer/CoreSimulator/Devices/FC163F57-3BF9-4CDA-9E24-DAA7C8EADBC1/data/Containers/Bundle/Application/A97B39AF-FC7A-4AC0-9503-C36DF7265780/NJEZPass.app/NJEZPass because dependent dylib #1 could not be loaded

**Comment by phabreeze** [comment]
yep same here. It appears to be linked to this issue --> https://stackoverflow.com/questions/52331634/xcode-10-0-gm-dyld-lazy-symbol-binding-failed-cant-resolve-symbol-cxa-gu

**Comment by yasirmturk** [comment]
I have updated the problematic [SDK](https://github.com/gali8/Tesseract-OCR-iOS/blob/5.0.1/TesseractOCRiOS.podspec)
Please wait for podspecs to be updated or override this lib in your own project's Podfile
`pod 'TesseractOCRiOS', '~> 5.0.1'` and then
`$ pod update TesseractOCRiOS`
clean, build and run
