### ISSUE TITLE
How do you compile the library for iOS

### ISSUE THREAD

**Issue by zhouhao27** [yasirmturk/openalpr-swift#4]
One question for you. How do you compile openalpr into iOS library? Thanks.

**Comment by yasirmturk** [comment]
Okay, [openalpr](https://github.com/openalpr/openalpr) is a C library so its can be compiled on any platform. [Here](https://github.com/twelve17/openalpr-ios) is the github project which compiles openalpr and dependencies for iOS platform 

But, you don't need to compile it yourself and you can also use [pre-built](https://github.com/yasirmturk/openalpr-swift/tree/master/lib/) frameworks as well, also [available here](https://github.com/cardash/react-native-openalpr/tree/master/ios/Frameworks)

**Comment by zhouhao27** [comment]
@yasirmturk Thanks for your reply. The reason I want to compile it by myself is that I may need to change something in openalpr.
