### ISSUE TITLE
Failed to run pod install

### ISSUE THREAD

**Issue by zhouhao27** [yasirmturk/openalpr-swift#5]
Got the following error message:

> [!] The 'Pods-OCRTest' target has transitive dependencies that include static binaries: (/Users/a635219/Projects/test/OCRTest/Pods/OpenCV/opencv2.framework)

**Comment by yasirmturk** [comment]
If you get an error complaining about "transitive dependencies" then put this in your Podfile

`pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end`

**Comment by zhouhao27** [comment]
Thanks. Didn't notice that in README.md.
