### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fnoyanisi** [yasirmturk/openalpr-swift#9]
Hi there,

The code comes under GPL-3 and cannot be used in any iOS app according to AppStore licensing rules.

**Comment by UBNT-brandongilles** [comment]
Oh, that's super-interesting.  Do you happen to have a source on GPL-3 not being allowed in the App Store (even for free apps)?

Thanks!

**Comment by fnoyanisi** [comment]
Well, I am not a lawyer nor work as a full-time software developer but based on my understanding of software licenses...
Any GPL’ed code requires the derivative work (i.e. the piece of software that relies on the GPL’ed code) to be open-source. There is a reason why XNU, llvm, Darwin, Swift are all released under a BSD-style permissive license rather than a fully copyleft license such as GPL. There are more permissive versions of GPL, such as LGPL which is used by software like GTK+ or FLTK (see difference between GPL in https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)
If your library is licensed under GPL, the code that is built on it, i.e. your App, has to be GPL licensed. The last time I checked, one cannot release an open-source software in the Apple AppStore.
Once you release your code under GPL, you cannot revoke it, i.e. you cannot change the license overnight and make it closed-source. But there are workarounds which I will not discuss here.
See this article from fsfhttps://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement
The fact that the App is “free” on the AppStore does not change the rules, everything put on the AppStore is subject to the same Apple software license agreement.
To complete the message, as usual in all license related discussions, I am not a legal advisor or lawyer and the best advice on the matter can be gotton from a lawyer.

**Comment by yasirmturk** [comment]
i am just using the original license offered by the open alpr project
https://github.com/openalpr/openalpr/blob/master/LICENSE

**Comment by fnoyanisi** [comment]
>> i am just using the original license offered by the open alpr project
I don’t think so. 
You are using GPL v3 whereas OpenALPR is AGPL v3, which, in fact, is more strict than GPL in terms of sharing the source code.
OpenALPR offers a commercial license, but you need to get in touch with the company for details.
You may want to have a look at LGPL but I am not sure whether GPL allows the owner to change the license to a more permissive one.
Appreciate the project and sharing it but need to be more cautious about the license you use.
    On Monday, October 29, 2018, 8:46:26 PM GMT+13, Yasir M Türk <notifications@github.com> wrote:  
 
 
i am just using the original license offered by the open alpr project
https://github.com/openalpr/openalpr/blob/master/LICENSE

**Comment by yasirmturk** [comment]
So, my project is open source anyway.. Does this mean that this can have impact on other people and app who want to use my library in their projects?

**Comment by fnoyanisi** [comment]
Well, in fact yes. I mean, your license is similar to the one used for the Linux kernel (Gpl v2 vs v3) and same as the one used for all GNU command line tools (you know, gnu tar, ls etc.). There is a reason why Playstation uses FreeBSD as its system software rather than the Linux kernel or macOS has BSD command line tools as opposed to GNU tools. Because GPL does not allow one to use/modify software and make it propriatery, whereas BSD (and alike) licences do. 
If your library were used by thosands of people, one could say “hang on a sec, by using this in an App, you are violating the software license you publish your framework under”. I think the worst consequence would be your App made disqualified for AppStore by Apple, but chances are low (fingers crossed).
Have a look at tldrlicense.org and if you want to publish sth for App developers, I think BSD or MIT style license is more appropriate.
As I said, I am not a software dev, mainly hanging around and doing hobby projects, so I do not want to mislead you.
By the way, your surname sounds turkish? Are you from turkey?
    On Monday, October 29, 2018, 9:17:00 PM GMT+13, Yasir M Türk <notifications@github.com> wrote:  
 
 
So, my project is open source anyway.. Does this mean that this can have impact on other people and app who want to use my library in their projects?

**Comment by Luxonis-Brandon** [comment]
> Well, I am not a lawyer nor work as a full-time software developer but based on my understanding of software licenses... Any GPL’ed code requires the derivative work (i.e. the piece of software that relies on the GPL’ed code) to be open-source. There is a reason why XNU, llvm, Darwin, Swift are all released under a BSD-style permissive license rather than a fully copyleft license such as GPL. There are more permissive versions of GPL, such as LGPL which is used by software like GTK+ or FLTK (see difference between GPL in https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) If your library is licensed under GPL, the code that is built on it, i.e. your App, has to be GPL licensed. The last time I checked, one cannot release an open-source software in the Apple AppStore. Once you release your code under GPL, you cannot revoke it, i.e. you cannot change the license overnight and make it closed-source. But there are workarounds which I will not discuss here. See this article from fsfhttps://[www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement](http://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement) The fact that the App is “free” on the AppStore does not change the rules, everything put on the AppStore is subject to the same Apple software license agreement. To complete the message, as usual in all license related discussions, I am not a legal advisor or lawyer and the best advice on the matter can be gotton from a lawyer.  From: UBNT-brandongilles <notifications@github.com> To: yasirmturk/openalpr-swift <openalpr-swift@noreply.github.com> Cc: Fehmi Noyan ISI <fnoyanisi@yahoo.com>; Author <author@noreply.github.com> Sent: Monday, October 29, 2018 2:03 AM Subject: Re: [yasirmturk/openalpr-swift] License (#9) Oh, that's super-interesting. Do you happen to have a source on GPL-3 not being allowed in the App Store (even for free apps)?Thanks!— You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thanks for the detailed response.  And also sorry I deleted my earlier question... I had asked it, somehow, with an old work account, and I haven't worked their for quite a while, so it definitely should not have been asked with that account.  Not quite sure how it happened actually, but anyways, thanks again for the details!

**Comment by peterdk** [comment]
Tried this library, with simple UIImage from AVCaptureStream. No results on proper images.

**Comment by yasirmturk** [comment]
@peterdk you need to down size the raw pictures from camera photo or video stream.. Does not produce results of hi-res frames
